apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  selector:
    matchLabels:
      app: go
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: registry.cn-beijing.aliyuncs.com/aliyun_chy/go:v1.3
        name: go
        imagePullPolicy: Always
        command: ["./main", "-v", "v1.3"]
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeName: chenhaoyu05029test
